---
abstract: 'extract information from LaTeX files'
author:
  - 'Andre Santos <andrefs@cpan.org>'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-TeXMine
requires:
  App::Rad: 0
  feature: 0
  perl: v5.14.1
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/andrefs/App-TeXMine/issues
  homepage: https://github.com/andrefs/App-TeXMine
  repository: git://github.com/andrefs/App-TeXMine.git
version: 0.01_13
